EcommerceWebApp/Controllers/UserloginController.cs
using EcommerceWebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EcommerceWebApp.Controllers
{
    public class UserloginController : Controller
    {
        // GET: Userlogin
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(ecom_adminUser admin_user)
        {
            //string username = "admin@admin.com";
            //string password = "Admin@2024";
            if (admin_user == null)
            {

            }
            else if (admin_user != null)
            {
                if (ModelState.IsValid)
                {
                    DB_ECOM_ENTITIES ecommerceEntities = new DB_ECOM_ENTITIES();

                    var obj=ecommerceEntities.ecom_adminUser.Where(e=> e.Username.Equals(admin_user.Username)&&e.Password.Equals(admin_user.Password)).FirstOrDefault();

                    if (obj != null)
                    {
                        Session["username"]=obj.Username.ToString();
                        Session["password"]=obj.Password.ToString();
                      return  RedirectToAction("Index", "Home");  
                    }
                }
            }
            return View(admin_user);
        }

    }
}

EcommerceWebApp/Views/Userlogin/login.cshtml
@model EcommerceWebApp.Models.ecom_adminUser
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AdminLTE 3 | Log in</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Content/admin/plugins/fontawesome-free/css/all.min.css">">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="~/Content/admin/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Content/admin/dist/css/adminlte.min.css">

    <body class="hold-transition login-page">
        <div class="login-box">
            <div class="login-logo">
                <a href="#"><b>Admin</b>LTE</a>
            </div>
            <!-- /.login-logo -->
            <div class="card">
                <div class="card-body login-card-body">
                    <p class="login-box-msg">Sign in to start your session</p>

                    @*<form action="#" method="post">*@
                    @using (Html.BeginForm("login", "Userlogin", FormMethod.Post))
                    {
                        <div class="input-group mb-3">
                            @*<input type = "email" class="form-control" placeholder="Email">*@

                            @Html.TextBoxFor(m => m.Username, new { @class = "form-control", placeholder = "Email" })

                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            @*<input type = "password" class="form-control" placeholder="Password">*@
                            @*@Html.PasswordFor(m => m.Password)*@
                            @Html.PasswordFor(m => m.Password, new { @class = "form-control", placeholder = "password" })
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-lock"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-8">
                                <div class="icheck-primary">
                                    <input type="checkbox" id="remember">
                                    <label for="remember">
                                        Remember Me
                                    </label>
                                </div>
                            </div>
                            <!-- /.col -->
                            <div class="col-4">
                                <button class="btn btn-primary btn-block">Sign In</button>
                            </div>
                            <!-- /.col -->
                        </div>
                        @*</form>*@
                    }
                        <h2>@ViewBag.email</h2>
                        <h2>@ViewBag.password</h2>
                   
                    <div class="social-auth-links text-center mb-3">
                        <p>- OR -</p>
                        <a href="#" class="btn btn-block btn-primary">
                            <i class="fab fa-facebook mr-2"></i> Sign in using Facebook
                        </a>
                        <a href="#" class="btn btn-block btn-danger">
                            <i class="fab fa-google-plus mr-2"></i> Sign in using Google+
                        </a>
                    </div>
                    <!-- /.social-auth-links -->

                    <p class="mb-1">
                        <a href="forgot-password.html">I forgot my password</a>
                    </p>
                    <p class="mb-0">
                        <a href="register.html" class="text-center">Register a new membership</a>
                    </p>
                </div>
                <!-- /.login-card-body -->
            </div>
        </div>
        <!-- /.login-box -->
        <!-- jQuery -->
        <script src="~/Content/admin/plugins/jquery/jquery.min.js"></script>
        <!-- Bootstrap 4 -->
        <script src="~/Content/admin/bootstrap/js/bootstrap.bundle.min.js"></script>
        <!-- AdminLTE App -->
        <script src="~/Content/admin/dist/js/adminlte.min.js"></script>

        <script>

        </script>
    </body>
</html>